### ISSUE TITLE
Docker Image Fails to Run: @prisma/client Initialization Error

### ISSUE THREAD

**Issue by alexindevs** [alexindevs/ShareX#1]
I encountered an issue with my Docker image where it builds successfully but fails to run. Upon attempting to run the image, I receive the following error:

```
/usr/src/app/node_modules/.prisma/client/index.js:43
    throw new Error(
    ^

Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/usr/src/app/node_modules/.prisma/client/index.js:43:11)
    at Object.<anonymous> (/usr/src/app/dist/models/auth.repository.js:8:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/usr/src/app/dist/services/auth.service.js:8:43)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
```

**Steps to Reproduce:**
1. Build the Docker image.
2. Attempt to run the Docker image.
3. Observe the error mentioned above.

**Expected Behavior:**
The Docker image should run successfully without any errors.

**Additional Information:**
- Node.js Version: 20.10.0
- Docker Image Configuration: 
```dockerfile
# syntax=docker/dockerfile:1

# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Dockerfile reference guide at
# https://docs.docker.com/go/dockerfile-reference/

ARG NODE_VERSION=20.10.0

################################################################################
# Use node image for base image for all stages.
FROM node:${NODE_VERSION}-alpine as base

# Set working directory for all build stages.
WORKDIR /usr/src/app

# Install ClamAV
RUN apk --no-cache add clamav clamav-daemon



# Configure ClamAV (create your own clamd.conf file and COPY it into the image)
# COPY clamd.conf /etc/clamav/clamd.conf

# Start ClamAV daemon
CMD ["clamd"]

################################################################################
# Create a stage for installing production dependecies.
FROM base as deps

# Change Alpine Linux mirror
RUN echo "https://dl-cdn.alpinelinux.org/alpine/v3.19/main" > /etc/apk/repositories && \
    echo "https://dl-cdn.alpinelinux.org/alpine/v3.19/community" >> /etc/apk/repositories

# Install bcrypt dependencies
RUN apk --no-cache add make g++ python3

# Download dependencies as a separate step to take advantage of Docker's caching.
# Leverage a cache mount to /root/.npm to speed up subsequent builds.
# Leverage bind mounts to package.json and package-lock.json to avoid having to copy them
# into this layer.
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci --omit=dev

################################################################################
# Create a stage for building the application.
FROM deps as build

# Download additional development dependencies before building, as some projects require
# "devDependencies" to be installed to build. If you don't need this, remove this step.
RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=package-lock.json,target=package-lock.json \
    --mount=type=cache,target=/root/.npm \
    npm ci

# Copy the rest of the source files into the image.
COPY . .
COPY prisma ./prisma/ 
RUN npx prisma generate

# Run the build script.
RUN npm run build

################################################################################
# Create a new stage to run the application with minimal runtime dependencies
# where the necessary files are copied from the build stage.
FROM base as final

# Use production node environment by default.
ENV NODE_ENV production

ENV NODE_PATH=/usr/src/app/node_modules


# Install ClamAV runtime dependencies
RUN apk --no-cache add libcurl libxml2 json-c

# Run the application as a non-root user.
USER node

# Copy package.json so that package manager commands can be used.
COPY package.json .

# Copy the production dependencies from the deps stage and also
# the built application from the build stage into the image.
COPY --from=deps /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist


# Expose the port that the application listens on.
EXPOSE 3000

# Run the application.
CMD npm start
```
- Prisma Configuration: [If applicable, provide any relevant Prisma configuration details here]

**Note:** I've already attempted to run `prisma generate` as suggested in the error message, but the issue persists.

**Comment by OcheOps** [comment]
Nothing is running from my end at all

**Comment by OcheOps** [comment]
Firstly the build command is not working

**Comment by alexindevs** [comment]
> Firstly the build command is not working 
> 

Um, it builds quite well on my end. Does it throw an error for you?
